/*Lab 3 - Capture and Compare with the MSP432
 *Part 1 - Measuring distance using the proximity sensor
 *
 *Authors:
 *  Renzo Garza Motta
 *  Cianna Janicke
 *
 *Class: EGR 326
 *Section: 903
 *
 *Instructor:
 *  Dr. Nabeeh Kandalaft
 *
 *Description:
 *  This part will use the MSP432 Timer A in Capture mode to determine the length
 *  of a pulse generated by a proximity sensor (HC-SR04).
 *  The proximity sensor must be pre-triggered in order to generate a pulse so that
 *  distance to an object can be determined.
 *
 *  -Connect the proximity sensor to the MSP432 such that:
 *      -MSP output pin is connected via a 2N7000 MOSFET to provide a 5V signal to
 *       the HC-SR04 Trigger pin.
 *      -HC-SR04 echo pin outputs a 5V signal that has to be stepped down to ~3.3V
 *       via a voltage divider to act as an input signal to the MSP432. The design
 *       used a 68kOhm and 36kOhm resistors for the voltage divider.
 *      -Additionally, Vcc = 5V and GND = 0V.
 *  -The program is to print the distance measured by the proximity sensor every
 *   2 sec to the console using printf() -- stdio.h was included to print to console.
 */

#include "msp.h"
#include <stdio.h>
#include "macros.h"
#include "systick.h"
#include "timerA.h"

uint8_t printFlag;
uint16_t currentEdge, lastEdge, deltaCycles;
double distCentimeter, distMilli;

void gpioSetup(void);
void setTrigger(void);
void sampleDistance(void);
void setupTimerA(void);

 void main(void){
	WDT_A->CTL = WDT_A_CTL_PW | WDT_A_CTL_HOLD;		// stop watchdog timer
	intSysTickSetup();  //Set up SysTick with an interrupt
	gpioSetup();        //Call GPIO set up function
	setupTimerA();      //Call Timer A setup function

	NVIC->ISER[0] = 1 << (TA3_N_IRQn & 31);     //Set Timer A0 interrupt vector
	__enable_irq();                             //Enable all interrupts

	while(1){
	    if(printFlag == 1){                     //Check if printFlag flag from SysTick Interrupt is set
	        sampleDistance();                   //Call function to sample distance from the US Sensor
	        //Ultrasonic Sensor is getting correct readings until the printf()
	        //statement is uncommented
//	        printf("%g\n", distCentimeter);
	        printFlag = 0;                      //Reset printFlag flag.
	    }
	}
}

void TA3_N_IRQHandler(void){
    double sigTime;
    currentEdge = TIMER_A3->CCR[1];             //Get "time" at which interrupt was triggered
    if(lastEdge > currentEdge){                 //Check for timer overflow
        currentEdge = currentEdge + 65534;      //If timer overflow happened, account for it by adding a full period length to the currentEdge
        deltaCycles = currentEdge - lastEdge;   //Determine the time difference between triggers
    }else{
        deltaCycles = currentEdge - lastEdge;   //Determine the time difference between triggers
    }
    lastEdge = currentEdge;                     //Set the new lastEdge as the latest edge time

    //Calculate the distance from deltaTime using speed of sound at sea level.
    //T = (1/3MHz) = 0.333 (us/clock cycle)
    sigTime = deltaCycles * 0.333;      //sigTime units is microseconds (us)
    distCentimeter = sigTime / 58;      //microseconds / 58 = centimeters => From HC-SR04 Datasheet
    distMilli = distCentimeter * 100;   //centimeter * 100 = millimeters

    TIMER_A3->CCTL[1] &=~ TIMER_A_CCTLN_CCIFG;  //Clear interrupt flag
}

void sampleDistance(void){
    setTrigger();   //Set the trigger of HC-SR04
}

void setTrigger(void){
    US_PORT->OUT &=~ TRIGGER;    //Set Trigger pin to send signal to US Sensor
    sysTickSetup();              //Initialize SysTick Timer
    usDelay(10);                 //Delay On-time for 10 us as per US Sensor Datasheet
    intSysTickSetup();           //Re-initialize SysTick Timer with an interrupt
    US_PORT->OUT |= TRIGGER;     //Clear Trigger pin to end trigger signal
}

void setupTimerA(void){
    TIMER_A3->CTL |= (TIMER_A_CTL_SSEL__SMCLK|         //Timer_A clock source: SMCLK
                      TIMER_A_CTL_MC__CONTINUOUS|      //Continuous mode: Timer counts to 0FFFFh
                      TIMER_A_CTL_ID__1|               //Input Divider of /1
                      TIMER_A_CTL_CLR);                //Clear TA0R

    TIMER_A3->CCTL[1] = (TIMER_A_CCTLN_CM__BOTH|       //Capture on both rising and falling edges
                         TIMER_A_CCTLN_CCIS__CCIA|     //Capture/Compare Input Select: CCIxA
                         TIMER_A_CCTLN_CCIE|           //capture/Compare Interrupt Enable
                         TIMER_A_CCTLN_CAP|            //Enable Capture mode
                         TIMER_A_CCTLN_SCS);           //Synchronize Capture source
}

void SysTick_Handler(void){
    printFlag = 1;              //Set flag to print values every time SysTick Interrupt is triggered (2sec)
}

void gpioSetup(void){
    //Set up 2.5 as TimerA instances to measure the time it take the signal to return to the sensor
    ECHO_PORT->SEL0 |= ECHO;
    ECHO_PORT->SEL1 &=~ ECHO;
    ECHO_PORT->DIR &=~ ECHO;      //Set up as input Timer A pin

    //Set up Ultrasonic Sensor trigger pin
    US_PORT->SEL0 &=~ TRIGGER;  //Set Pin 2.5 as GPIO to connect to Ultrasonic Sensor
    US_PORT->SEL1 &=~ TRIGGER;
    US_PORT->DIR |= TRIGGER;    //Set pin connected to Ultrasonic Sensor Trigger as output
    US_PORT->OUT |= TRIGGER;    //Set trigger pin to low to avoid accidental sampling
}
